spring:
  application:
    name: showcase

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: showcase
    password: doubleSlash
    driver-class-name: org.h2.Driver

  jpa:
    database: H2
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  h2:
      console:
        enabled: true

server:
  port: 8090

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        data: DEBUG
        orm: DEBUG
        hibernate: DEBUG
        flywaydb: DEBUG